<?php namespace ProcessWire;

class ResponsiveImage extends WireData implements Module {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(

			'title' => 'ResponsiveImage',
			'version' => 100,
			'summary' => 'Einfache Erstellung von Responsive-optimierten img-tags .',
			//'href' => 'https://processwire.com',
            'icon' => 'picture-o',

            // Nur eine Instanz, da wir Hooks benutzen
            'singular' => true,

            // autoload=true: indicates the module should be started with ProcessWire.
            // This is necessary for any modules that attach runtime hooks, otherwise those
            // hooks won't get attached unless some other code calls the module on it's own.
            // Note that autoload modules are almost always also 'singular' (seen above).
            'autoload' => true,

			);
	}

	/**
	 * Initialize the module
	 *
	 * ProcessWire calls this when the module is loaded. For 'autoload' modules, this will be called
	 * when ProcessWire's API is ready. As a result, this is a good place to attach hooks. 
	 *
	 */
	public function init() {

        $this->addHook('Page::noResponsiveImage', $this, 'noResponsiveImages');
        $this->addHook('Pageimage::responsiveImage', $this, 'responsiveImage');
        $this->addHook('Pageimage::responsiveBackground', $this, 'responsiveBackground');
        $this->addHook('Page::getResponsiveCSS', $this, 'getResponsiveCSS');

	}


   public function responsiveImage($event) {

        if (!$this->useModule()) {
            return "Modul deaktiviert"; //todo: standardbild ausliefern
        }
        $image = $event->object;
        $attributes = $this->createAttributeString($event['arguments'][1]);

       $srcset = $this->createSizeArray($event['arguments'][0]);
       $srcset = $this->createSrcset($srcset);

        $return =
            '<img ' .
            'src="'. $image->url . '" ' .
            'alt="' . $image->width . "x" . $image->height . '"' .
            'srcset="' . $srcset . '" ' .
            $this->createAttributeString($attributes).
            '>';

        //$event->return = '** '. var_dump($event); die() . '**';
        $event->return = $return;
        //$event->return = '** '. $event->object->url . '**';
    }

    public function responsiveBackground($event){
        $return = '';
        $event->return = $return;
    }

    private function createSizeArray($options){

        $return = $this->defaultSizeArray;

        foreach ($return as $key => $value) {
            if (isset($options[$key]) && is_numeric($options[$key])) {
                $return[$key] = $value;
            } elseif (isset($options[$key]) && $options[$key] == false) {
                unset($return[$key]);
            } elseif (!isset($options[$key]) ) {
                unset($return[$key]);
            } elseif (isset($options[$key]) && is_object($options[$key])) {
                $return[$key] = $options[$key]->width;
            }
        }
        var_dump($return);
        return $return;
    }

    private function createSrcset($sizes){
        return implode(", ", $sizes);
    }

    private function createAttributeString($attributes){
        return implode(" ", $attributes);
    }

    private $defaultSizeArray = array(
        'xl' => 1920,
        'lg' => 1600,
        'md' => 1200,
        'sm' => 992,
        'xs' => 768
    );

    private function useModule(){
        return true;
    }

}

